[package]
org = "wso2healthcare"
name = "test3"
version = "0.1.2"
export = ["test3"]
distribution = "2201.2.3"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Patient","r4","international"]

[build-options]
observabilityIncluded = true
